My_travel_to/My_travel_to/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mytravelto_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('my_travel_to/', include('mytravelto_app.urls')),
    path('logout/', views.user_logout, name='logout'),

]

My_travel_to/mytravelto_app/urls.py
from django.conf.urls import url
from mytravelto_app import views

#TEMPLATE URLS!
app_name = 'mytravelto_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

My_travel_to/mytravelto_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.PROTECT)

    #additional
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

My_travel_to/mytravelto_app/forms.py
from django import forms
from django.contrib.auth.models import User
from mytravelto_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model  = UserProfileInfo
        fields = ('profile_pic', )

My_travel_to/mytravelto_app/views.py
from django.shortcuts import render
from mytravelto_app.forms import UserForm, UserProfileInfoForm

#login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request,'mytravelto_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

#@login_required
#def feed(request):
    #the user's newsfeed

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'mytravelto_app/registration.html',
        {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and Password: {}".format(username, password))
            return HttpResponse('invalid login details supplied!')
    else:
        return render(request, 'mytravelto_app/login.html', {})

My_travel_to/templates/mytravelto_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>My travel to...</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/my_travel_to_style.css' %}">
  </head>
  <body class='bg-dark text-light'>
    <nav class="navbar navbar-expand-sm bg-warning navbar-light">
      <a class='navbar-brand ml-2 mt-auto h1' href="{%url 'index'%}">My travel to...</a>
      <button class="navbar-toggler ml-auto mr-2" type="button" data-toggle="collapse" data-target="#myNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse ml-2 mt-2 mb-0" id="myNav">
        <ul class='navbar-nav'>
          <li class='nav-item'>
            <a class='nav-link' href="{%url 'index'%}">Home</a>
          </li>
          <li class='nav-item'>
            <a class='nav-link' href="{%url 'mytravelto_app:register'%}">Register</a>
          </li>
          {% if user.is_authenticated %}
            <li><a class='nav-link' href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class='nav-link' href="{% url 'mytravelto_app:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
        <form class="form-inline ml-auto mr-2" action="/action_page.php">
          <input class="form-control mr-sm-2 " type="text" placeholder="Search"><br>
          <button class="btn btn-dark mt-2 mb-2 ml-auto" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container">

      {% block body_block %}
      <!-- Tudo dentro desse bloco vai ser adicionado de outros arquivos html -->
      {% endblock %}
    </div>

    <footer>
      <br><br>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>

My_travel_to/templates/mytravelto_app/index.html
{% extends 'mytravelto_app/base.html' %}
{% load static %}

{% block body_block %}
  <div class="row my-5">
    <div class="col-sm-6 d-flex align-items-center">
      <div class="">
        <h1>My travel to... What I mean?</h1>
        <p>I mean.. Why not to register the place that I went in a social media to other people see how actually that place is?</p>
        <p>So, if you want to know the place before you go, why not just search in My travel to...?</p>
        <p>You can be anywhere, anytime you want. You can know the world just with one click!</p>
      </div>
    </div>
    <div class="col-sm-6">
      <img class="img-fluid" src="{% static 'img/self.png' %}" alt="Leblon Ocean">
    </div>
  </div>
  <div class="row my-5">
    <div class="col-sm-6">
      <img class='img-fluid' src="{% static 'img/selfgif.gif'%}" alt="">
    </div>
    <div class="col-sm-6 d-flex align-items-center">
      <div class="">
        <p>The idea is to people post photos in front the new coffee shop, or maybe that bar in the new city you want to go next summer.</p>
        <p>You just post your photos to share the location to other people check the experience that you have. Describe, give a note, classify what you thoght about the place and share.</p>
      </div>
      </div>
  </div>
{% endblock %}

My_travel_to/templates/mytravelto_app/login.html
{% extends 'mytravelto_app/base.html'%}
{% block body_block%}
<br><br>
<h1 class='text-center'>Please Login</h1><br>
<div class="row">
  <div class="col-sm d-flex justify-content-center">
      <div class='table-responsive-sm'>
          <form action="{% url 'mytravelto_app:user_login' %}" method="post">
              <table class='table table-striped'>
                {%csrf_token%}
                <tr>
                  <td><label for="username">Username:</label></td>
                  <td><input type="text" name="username" placeholder="Enter Username"></td>
                </tr>
                <tr>
                  <td><label for="password">Password:</label></td>
                  <td><input type="password" name="password"></td>
                </tr>
              </table>
              <input class='container btn btn-warning' type="submit" value="Login">
            </form>
      </div>
  </div>
</div>

{%endblock%}

My_travel_to/templates/mytravelto_app/registration.html
{% extends 'mytravelto_app/base.html' %}
{% load static %}

{% block body_block %}
<br><br>
<div class='row'>
  {% if registered %}
    <div class='col-sm'>
        <h1 class='text-center'>Thank you for registering!</h1>
    </div>
  {% else %}
    <div class="col-sm">

        <h1 class='text-center'>Register Here</h1>
        <h3 class='text-center'>Fill out the form: </h3><br>
        <div class='table-responsive-sm'>
          <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
                <table class='table table-striped'>
                  {{user_form.as_table}}
                  {{profile_form.as_table}}
                </table>

            <input class='btn btn-warning container' type="submit" name="" value="Register">
          </form>
      </div>
    </div>

  {% endif %}
</div>
{% endblock %}